language: node_js
node_js:
  - 13

services:
  - docker

install:
  - echo "nothing needs to be installed"

before_script:
  - echo "no tests"

script:
  - docker --version
  - cd project
  - docker-compose -f docker-compose-build.yaml build --parallel
  - docker tag udagram-api-feed dilllip/udagram-api-feed:latest

after_success:
  - cd project
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push dilllip/udagram-api-feed:latest
