apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-api-feed
  labels:
    service: udagram-api-feed
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udagram-api-feed
  template:
    metadata:
      labels:
        service: udagram-api-feed
    spec:
      restartPolicy: Always
      containers:
        - image: dilllip/udagram-api-feed
          name: udagram-api-feed
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "2048Mi"
              cpu: "500m"
          env:
            # Similar to docker-compose.yaml
            # POSTGRES
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: POSTGRES_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: env-configmap
                  key: POSTGRES_DB
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: env-configmap
                  key: POSTGRES_HOST

            # AWS
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: env-configmap
                  key: AWS_REGION
            - name: AWS_PROFILE
              valueFrom:
                configMapKeyRef:
                  name: env-configmap
                  key: AWS_PROFILE
            - name: AWS_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: env-configmap
                  key: AWS_BUCKET

            # MISC
            - name: URL
              valueFrom:
                configMapKeyRef:
                  name: env-configmap
                  key: URL

            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: JWT_SECRET
